export enum ValorizationActionsFilterEnum {
  FIND_CONTRACT = 'FIND_CONTRACT',
  SHOW_CONTRACT = 'SHOW_CONTRACT',
  FIND_CONTRACT_CREATE = 'FIND_CONTRACT_CREATE',
  REVALORIZE = 'REVALORIZE',
  UPDATE_TAXATION = 'UPDATE_TAXATION',
  UPDATE_TAXATION_START = 'UPDATE_TAXATION_START',
  SINGLETOREVALORIZE = 'SINGLETOREVALORIZE',
  UPDATE_TC = 'UPDATE_TC',
  UPDATE_SC = 'UPDATE_SC'
}

export enum CustomerFileValorizationActionsEnum {
  STANDARD = 'STANDARD',
  REFRESH_TRANSPORT_CONTRACTS = 'REFRESH_TRANSPORT_CONTRACTS',
  REFRESH_SERVICE_CONTRACTS = 'REFRESH_SERVICE_CONTRACTS',
  REPLACE_NOT_INVOICED_CONTRACTS = 'REPLACE_NOT_INVOICED_CONTRACTS',
  REPLACE_IN_ERROR_CONTRACTS = 'REPLACE_IN_ERROR_CONTRACTS',
  REPLACE_ALL_CONTRACTS = 'REPLACE_ALL_CONTRACTS'
}
