export enum InitialDistanceCalculator {
  GOOGLE = 'GOOGLE',
  PTV_TRUCK40T = 'PTV-TRUCK40T',
  PTV_TRUCK11_99T = 'PTV-TRUCK11_99T',
  PTV_TRUCK7_49T = 'PTV-TRUCK7_49T',
  PTV_TRAILERTRUCK = 'PTV-TRAILERTRUCK',
  PTV_7_MEDIUM_TRACTOR = 'PTV-7_MEDIUM_TRACTOR',
  PTV_8_DOUBLE_TRAILER = 'PTV-8_DOUBLE_TRAILER',
  PTV_8_HEAVY_TRACTOR = 'PTV-8_HEAVY_TRACTOR',
  PTV_8_SEMITRAILER_3AXLE = 'PTV-8_SEMITRAILER_3AXLE',
  PTV_8_SEMITRAILER_4AXLE = 'PTV-8_SEMITRAILER_4AXLE',
  PTV_8_SEMITRAILER_5AXLE = 'PTV-8_SEMITRAILER_5AXLE',
  PTV_CAR = 'PTV-CAR',
  PTV_BICYCLE = 'PTV-BICYCLE',
  PTV_PEDESTRIAN = 'PTV-PEDESTRIAN'
}
