export enum EmptyDistanceRetributionOption {
  EMPTY_DISTANCE_BEFORE_TRIP = 'EMPTY_DISTANCE_BEFORE_TRIP',
  EMPTY_DISTANCE_AFTER_TRIP = 'EMPTY_DISTANCE_AFTER_TRIP',
  NO_EMPTY_DISTANCE_RETRIBUTION = 'NO_EMPTY_DISTANCE_RETRIBUTION'
}
export const EMPTY_DISTANCE_RETRIBUTION_OPTIONS = Object.values(EmptyDistanceRetributionOption);
