export enum PricingFormula {
  VIN_FIXED = 'VIN_FIXED',
  VIN_KM = 'VIN_KM',
  VIN_RANGE = 'VIN_RANGE',
  VIN_CATEGORY_FIXED = 'VIN_CATEGORY_FIXED',
  VIN_CATEGORY_KM = 'VIN_CATEGORY_KM',
  VIN_CATEGORY_RANGE = 'VIN_CATEGORY_RANGE',
  TRIP_FIXED = 'TRIP_FIXED',
  TRIP_KM = 'TRIP_KM',
  TRIP_RANGE = 'TRIP_RANGE',
  TRIP_CATEGORY_FIXED = 'TRIP_CATEGORY_FIXED',
  TRIP_CATEGORY_KM = 'TRIP_CATEGORY_KM',
  TRIP_CATEGORY_RANGE = 'TRIP_CATEGORY_RANGE',
  PRICING_GRID = 'PRICING_GRID',
  PRICING_CLIENT = 'PRICING_CLIENT',
  DAY = 'DAY',
  DISTANCE = 'DISTANCE',
  DAY_DISTANCE = 'DAY_DISTANCE',
  DISTANCE_RANGE = 'DISTANCE_RANGE'
}
export const PRICING_FORMULAS = Object.values(PricingFormula);

export enum TransportRoadContractPricingFormula {
  VIN_FIXED = 'VIN_FIXED',
  VIN_KM = 'VIN_KM',
  VIN_RANGE = 'VIN_RANGE',
  VIN_CATEGORY_FIXED = 'VIN_CATEGORY_FIXED',
  VIN_CATEGORY_KM = 'VIN_CATEGORY_KM',
  VIN_CATEGORY_RANGE = 'VIN_CATEGORY_RANGE',
  TRIP_FIXED = 'TRIP_FIXED',
  TRIP_KM = 'TRIP_KM',
  TRIP_RANGE = 'TRIP_RANGE',
  TRIP_CATEGORY_FIXED = 'TRIP_CATEGORY_FIXED',
  TRIP_CATEGORY_KM = 'TRIP_CATEGORY_KM',
  TRIP_CATEGORY_RANGE = 'TRIP_CATEGORY_RANGE',
  PRICING_GRID = 'PRICING_GRID',
  PRICING_CLIENT = 'PRICING_CLIENT'
}

export const TRANSPORT_ROAD_CONTRACT_PRICING_FORMULAS = Object.values(TransportRoadContractPricingFormula);

export enum TransportContractPricingFormula {
  VIN_FIXED = 'VIN_FIXED',
  VIN_KM = 'VIN_KM',
  VIN_RANGE = 'VIN_RANGE',
  VIN_CATEGORY_FIXED = 'VIN_CATEGORY_FIXED',
  VIN_CATEGORY_KM = 'VIN_CATEGORY_KM',
  VIN_CATEGORY_RANGE = 'VIN_CATEGORY_RANGE',
  PRICING_GRID = 'PRICING_GRID',
  PRICING_CLIENT = 'PRICING_CLIENT'
}

export const TRANSPORT_CONTRACT_PRICING_FORMULAS = Object.values(TransportContractPricingFormula);
